-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgKpFUgBXoL2fg+k8R
nN6mdfHr2LXNXSDHTvyihc7DKDigCgYIKoZIzj0DAQehRANCAAREWW2Z+1ri9tGx
P587NY3D+mg/a1ERZVjRdql1fJFBL3Dxr4ezyNBaNzwvpx0vEv4ygJKgifqMzBl+
8eF3OjkE
-----END PRIVATE KEY-----