name: conic
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  better_player: 
  cached_network_image: ^3.0.0
  cloud_firestore: ^2.1.0
  contacts_service: ^0.6.1
  cupertino_icons: ^1.0.2
  file_picker: ^4.1.0
  firebase_auth: ^1.1.4
  firebase_core: ^1.1.1
  firebase_dynamic_links: ^2.0.3
  firebase_storage: ^8.0.6
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.1.2
  flutter_hooks: ^0.16.0
  flutter_login_facebook: ^1.0.1
  flutter_screenutil: ^5.0.0+2
  geoflutterfire2: ^2.3.6
  geolocator: ^7.0.3
  get: ^4.1.4
  google_sign_in: ^5.0.3
  hooks_riverpod: ^0.14.0+3
  image_cropper: ^1.4.0
  image_picker: ^0.7.5+3
  intl: ^0.17.0
  loading_overlay: ^0.3.0
  nfc_manager: ^3.0.0+2
  open_settings:
    git:
      url: https://github.com/marcojoao/open_settings
  pdf_render: ^1.0.12
  permission_handler: ^8.0.0+2
  ripple_animation:
    git:
      url: https://github.com/PoloLacoste/ripple_animation
  shared_preferences: ^2.0.6
  sign_in_with_apple: ^3.1.0
  url_launcher: ^6.0.4
  velocity_x: ^3.0.0
  video_thumbnail: ^0.4.3

flutter_native_splash:
  color: "ffffff"
  color_dark: "F6F8FB"
  android_disable_fullscreen: true
  android: true
  ios: true

dev_dependencies:
  flutter_native_splash: null
  flutter_test:
    sdk: flutter
flutter:

  uses-material-design: true
  assets:
    - images/

  fonts:
    - family: montserrat
      fonts:
        - asset: fonts/Montserrat-ExtraLight.ttf
          weight: 100
        - asset: fonts/Montserrat-Thin.ttf
          weight: 200
        - asset: fonts/Montserrat-Light.ttf
          weight: 300
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-Semibold.ttf
          weight: 600
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: fonts/Montserrat-Black.ttf
          weight: 900
